### ISSUE TITLE
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 10.0.2-internal

### ISSUE THREAD

**Issue by eritter688** [eritter688/jMoria#1]
Reminder to make sure that Java 11 and JavaFX are playing nicely together.

**Comment by JanDa-ma** [comment]
How did you fixed the problem?

**Comment by Haris-Noori** [comment]
Any solution ?

**Comment by eritter688** [comment]
https://stackoverflow.com/questions/35210120/javafx-fxml-api-version-warning

See the top rated answer. I changed the versioning in the FXML files to the version it was looking for and the error has gone away. My FXML is not overly complicated and I have not run into any issues with the code as it is so I assume the change in version has not caused any compatibility problems. YMMV.

**Comment by yamanidev** [comment]
Your answer does solve the problem, if you're writing FXML by hand so thank you for it!
However, I am using Scene Builder and whenever I save the FXML document through Scene Builder, it overwrites the attribute change I applied previously to the xmlns attribute, any thoughts?
